spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/flagship_db
    username: flagship_user
    password: flagship_password
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/flagship
          jwk-set-uri: http://keycloak:8080/realms/flagship/protocol/openid-connect/certs
  
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    com.flagship.user: INFO
    org.springframework.security: WARN
    org.springframework.kafka: WARN

keycloak:
  auth-server-url: http://keycloak:8080
