[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests -Prailway"

[deploy]
startCommand = "echo 'All services built successfully. To deploy individual services, create separate Railway services with root directories:' && echo '  - services/api-gateway (Port: 8081)' && echo '  - services/user-service (Port: 8082)' && echo '  - services/order-service (Port: 8083)' && echo '  - services/payment-service (Port: 8084)' && echo '  - services/inventory-service (Port: 8085)' && echo '  - services/streaming-service (Port: 8086)' && echo 'All JAR files:' && find services -name '*.jar' -type f -exec echo 'JAR: {}' \\;"
healthcheckPath = "/actuator/health"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"