[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests -Prailway"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
