[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests -Prailway"

[deploy]
startCommand = "echo 'All services built successfully. Check Railway dashboard for individual service deployments.' && find services -name '*.jar' -type f -exec echo 'Built: {}' \\;"
healthcheckPath = "/actuator/health"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"