[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests -Prailway"

[deploy]
startCommand = "echo 'Multi-module project - all services built successfully' && find services -name '*.jar' -type f"
healthcheckPath = "/actuator/health"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"

# Define multiple services
[[services]]
name = "api-gateway"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/api-gateway -am"
startCommand = "java -jar services/api-gateway/target/api-gateway-1.0.0.jar"
port = 8081

[[services]]
name = "user-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/user-service -am"
startCommand = "java -jar services/user-service/target/user-service-1.0.0.jar"
port = 8082

[[services]]
name = "order-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/order-service -am"
startCommand = "java -jar services/order-service/target/order-service-1.0.0.jar"
port = 8083

[[services]]
name = "payment-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/payment-service -am"
startCommand = "java -jar services/payment-service/target/payment-service-1.0.0.jar"
port = 8084

[[services]]
name = "inventory-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/inventory-service -am"
startCommand = "java -jar services/inventory-service/target/inventory-service-1.0.0.jar"
port = 8085

[[services]]
name = "streaming-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/streaming-service -am"
startCommand = "java -jar services/streaming-service/target/streaming-service-1.0.0.jar"
port = 8086