# Railway Multi-Service Configuration
# This file defines all microservices for automatic deployment

[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests -Prailway"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"

# API Gateway Service
[[services]]
name = "api-gateway"
source = "services/api-gateway"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/api-gateway -am"
startCommand = "java -jar target/api-gateway-1.0.0.jar"
healthcheckPath = "/actuator/health"
[services.env]
SERVER_PORT = "8081"

# User Service
[[services]]
name = "user-service"
source = "services/user-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/user-service -am"
startCommand = "java -jar target/user-service-1.0.0.jar"
healthcheckPath = "/actuator/health"
[services.env]
SERVER_PORT = "8082"

# Order Service
[[services]]
name = "order-service"
source = "services/order-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/order-service -am"
startCommand = "java -jar target/order-service-1.0.0.jar"
healthcheckPath = "/actuator/health"
[services.env]
SERVER_PORT = "8083"

# Payment Service
[[services]]
name = "payment-service"
source = "services/payment-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/payment-service -am"
startCommand = "java -jar target/payment-service-1.0.0.jar"
healthcheckPath = "/actuator/health"
[services.env]
SERVER_PORT = "8084"

# Inventory Service
[[services]]
name = "inventory-service"
source = "services/inventory-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/inventory-service -am"
startCommand = "java -jar target/inventory-service-1.0.0.jar"
healthcheckPath = "/actuator/health"
[services.env]
SERVER_PORT = "8085"

# Streaming Service
[[services]]
name = "streaming-service"
source = "services/streaming-service"
buildCommand = "mvn clean package -DskipTests -Prailway -pl services/streaming-service -am"
startCommand = "java -jar target/streaming-service-1.0.0.jar"
healthcheckPath = "/actuator/health"
[services.env]
SERVER_PORT = "8086"