[build]
builder = "dockerfile"

[env]
JAVA_TOOL_OPTIONS = "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"
SPRING_PROFILES_ACTIVE = "railway"

# ---------------- API Gateway ----------------
[[services]]
name = "api-gateway"
root = "services/api-gateway"
dockerfilePath = "Dockerfile"
healthcheckPath = "/actuator/health"

# ---------------- Inventory Service ----------------
[[services]]
name = "inventory-service"
root = "services/inventory-service"
dockerfilePath = "Dockerfile"
healthcheckPath = "/actuator/health"