[build]
builder = "dockerfile"

[env]
JAVA_TOOL_OPTIONS = "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"

# ---------------- API Gateway ----------------
[[services]]
name = "api-gateway"
root = "/services/api-gateway"
dockerfilePath = "/services/api-gateway/Dockerfile"
healthcheckPath = "/actuator/health"