[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar services/api-getway/target/api-gateway-1.0.0.jar"
healthcheckPath = "/actuator/health"
port = 8081
healthcheckTimeout = "30s"
healthcheckInterval = "10s"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"
SERVER_PORT = "8081"
MANAGEMENT_SERVER_PORT = "8081"
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE = "health,info,metrics,prometheus,gateway"
MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS = "always"
MANAGEMENT_ENDPOINTS_WEB_BASE_PATH = "/actuator"