spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/flagship
          jwk-set-uri: http://keycloak:8080/realms/flagship/protocol/openid-connect/certs
  
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    com.flagship: INFO