[build]
builder = "railpack"
buildCommand = "cd ../.. && mvn clean package -DskipTests -Prailway -pl services/streaming-service -am"

[deploy]
startCommand = "java -jar target/streaming-service-1.0.0.jar"
healthcheckPath = "/actuator/health"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"
SERVER_PORT = "8086"