spring:
  data:
    redis:
      host: redis
      port: 6379
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/flagship
          jwk-set-uri: http://keycloak:8080/realms/flagship/protocol/openid-connect/certs

logging:
  level:
    com.flagship.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: WARN
