server:
  port: ${PORT:8081}
  address: 0.0.0.0
  netty:
    connection-timeout: 20000
    max-initial-line-length: 4096
    max-header-size: 8192
    max-chunk-size: 8192
    initial-buffer-size: 128
    enable-access-log: false

spring:
  application:
    name: ${APP_NAME:unknown}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8080/realms/flagship}
          jwk-set-uri: ${JWK_URI:http://localhost:8080/realms/flagship/protocol/openid-connect/certs}

  # Redis configuration for Railway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 4
          max-idle: 2
          min-idle: 0
          max-wait: 1000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway,env
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    redis:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms
  prometheus:
    metrics:
      export:
        enabled: true
  jvm:
    memory:
      enabled: true

logging:
  level:
    com.flagship.gateway: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.security: WARN
    org.springframework.web.reactive: WARN
    reactor.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 5
        minimum-number-of-calls: 3
      order-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 5
        minimum-number-of-calls: 3
      payment-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 5
        minimum-number-of-calls: 3
      inventory-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 5
        minimum-number-of-calls: 3
      streaming-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 5
        minimum-number-of-calls: 3

  ratelimiter:
    instances:
      default:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0s
        register-health-indicator: true

spring.cloud.gateway:
  redis-rate-limiter:
    replenish-rate: 5
    burst-capacity: 10
    requested-tokens: 1
  httpclient:
    connect-timeout: 5000
    response-timeout: 10s
    pool:
      max-connections: 50
      max-idle-time: 30s
      max-life-time: 60s
  webflux:
    base-path: /
  metrics:
    enabled: true
