[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/order-service-1.0.0.jar"
healthcheckPath = "/actuator/health"
port = 8083
healthcheckTimeout = "30s"
healthcheckInterval = "10s"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"
SERVER_PORT = "8083"
MANAGEMENT_SERVER_PORT = "8083"
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE = "health,info,metrics,prometheus"
MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS = "always"
MANAGEMENT_ENDPOINTS_WEB_BASE_PATH = "/actuator"
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"