[build]
builder = "railpack"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/order-service-1.0.0.jar"
healthcheckPath = "/actuator/health"

[env]
RAILPACK_JAVA_VERSION = "21"
JAVA_VERSION = "21"
SPRING_PROFILES_ACTIVE = "docker"
SERVER_PORT = "8083"